name: esotelo-app

services:
  db:
    build:
      context: ./containers/postgresql
    container_name: postgresql
    volumes:
      - ./volumes/tmp:/tmp:Z
      - ./volumes/db_backups:/backups:Z
      - ./volumes/queries:/queries:Z
    ports:
      - 5432:5432
    tty: true
    stdin_open: true
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql-password
      - PGDATA=/var/lib/postgresql/data/pgdata
    secrets:
      - postgresql-password
    networks:
      backend:
        ipv4_address: 172.18.0.2

  db-admin:
    build:
      context: ./containers/pgadmin
    container_name: pgadmin
    volumes:
      - ./volumes/queries:/var/lib/pgadmin/storage:Z
    ports:
      - 9088:80
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=sotelo.enrique@gmail.com
      - PGADMIN_DEFAULT_PASSWORD_FILE=/run/secrets/pgadmin-password
    secrets:
      - pgadmin-password
    networks:
      backend:
        ipv4_address: 172.18.0.3

  web-php:
    build:
      context: ./containers/apache-php
    container_name: apache-php
    volumes:
      - ./volumes/tmp:/tmp:Z
      - ./volumes/apache_docs:/var/www/html:Z
    ports:
      - 80:80
    tty: true
    stdin_open: true
    depends_on:
      - db
    networks:
      backend:
        ipv4_address: 172.18.0.4

networks:
  backend:
    ipam:
      config:
        - subnet: 172.18.0.0/24

secrets:
  postgresql-password:
    file: ./containers/secrets/postgresql-password.txt
  pgadmin-password:
    file: ./containers/secrets/pgadmin-password.txt
